import os
import subprocess
import json

def get_video_duration(input_file):
    """Gets the duration of the video in seconds using ffprobe."""
    cmd = [
        "ffprobe", 
        "-v", "error", 
        "-show_entries", "format=duration", 
        "-of", "default=noprint_wrappers=1:nokey=1", 
        input_file
    ]
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return float(result.stdout.strip())

def compress_video(input_file, output_file, target_size_mb=9.5):
    """Compresses a video to a target size (default slightly under 10MB for safety)."""
    
    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found.")
        return

    # Target size in kilobits (1 MB = 8192 kilobits)
    target_size_kb = target_size_mb * 8192
    
    duration = get_video_duration(input_file)
    print(f"Video Duration: {duration:.2f} seconds")
    
    # Calculate target total bitrate (kbps)
    target_total_bitrate = target_size_kb / duration
    
    # Allocate 128 kbps for audio, the rest for video
    audio_bitrate = 128
    video_bitrate = max(100, int(target_total_bitrate - audio_bitrate))
    
    print(f"Target Video Bitrate: {video_bitrate}k")
    print(f"Target Audio Bitrate: {audio_bitrate}k")
    
    # FFmpeg command
    cmd = [
        "ffmpeg",
        "-y", # Overwrite output file if it exists
        "-i", input_file,
        "-vcodec", "libx264",
        "-b:v", f"{video_bitrate}k",
        "-pass", "1",
        "-an", # No audio for first pass
        "-f", "mp4",
        os.devnull # Output to null for first pass
    ]
    
    print("Starting Pass 1...")
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    cmd = [
        "ffmpeg",
        "-y",
        "-i", input_file,
        "-vcodec", "libx264",
        "-b:v", f"{video_bitrate}k",
        "-pass", "2",
        "-acodec", "aac",
        "-b:a", f"{audio_bitrate}k",
        output_file
    ]
    
    print("Starting Pass 2...")
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # Cleanup log files generated by 2-pass encoding
    for file in os.listdir('.'):
        if file.startswith('ffmpeg2pass'):
            os.remove(file)
            
    final_size = os.path.getsize(output_file) / (1024 * 1024)
    print(f"Compression Complete! Final size: {final_size:.2f} MB")

# --- Usage ---
input_video = "your_video.mp4"    # Replace with your video file name
output_video = "compressed_video.mp4"

compress_video(input_video, output_video)